2024-12-12 14:24:45,323 - INFO - Starting the application...
2024-12-12 14:24:45,335 - INFO - Application output:

2024-12-12 14:41:39,360 - INFO - Starting the application...
2024-12-12 14:41:39,717 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import app as transfer_app
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import app as transfer_app
ModuleNotFoundError: No module named 'api.wallet'; 'api' is not a package

2024-12-12 14:43:28,875 - INFO - Starting the application...
2024-12-12 14:43:28,885 - ERROR - Error occurred: python3: can't open file '/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py': [Errno 2] No such file or directory

2024-12-12 14:45:20,978 - INFO - Starting the application...
2024-12-12 14:45:21,348 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import app as transfer_app
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import app as transfer_app
ModuleNotFoundError: No module named 'api.wallet'; 'api' is not a package

2024-12-12 14:45:43,597 - INFO - Starting the application...
2024-12-12 14:45:43,910 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
ModuleNotFoundError: No module named 'api.wallet'; 'api' is not a package

2024-12-12 14:50:05,992 - INFO - Starting the application...
2024-12-12 14:50:06,348 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
ModuleNotFoundError: No module named 'api.wallet'; 'api' is not a package

2024-12-12 14:52:22,736 - INFO - Starting the application...
2024-12-12 14:52:23,032 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from .wallet.transfer import transfer_sol
ImportError: attempted relative import with no known parent package

2024-12-12 14:55:48,170 - INFO - Starting the application...
2024-12-12 14:55:48,545 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
ModuleNotFoundError: No module named 'api.wallet'; 'api' is not a package

2024-12-12 14:57:17,034 - INFO - Starting the application...
2024-12-12 14:57:17,325 - ERROR - Error occurred: Traceback (most recent call last):
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
  File "/home/exril/Documents/codeas/memepay/memepay-backend/memepay-backend-rw/api/api.py", line 2, in <module>
    from api.wallet.transfer import transfer_sol
ModuleNotFoundError: No module named 'api.wallet'; 'api' is not a package

2024-12-12 15:02:06,572 - INFO - Starting the application...
2024-12-12 15:04:01,758 - INFO - Starting the application...
2024-12-12 15:04:58,570 - INFO - Starting the application...
2024-12-12 15:04:58,841 - ERROR - Error occurred: No module named 'wallet'
2024-12-12 15:13:51,403 - INFO - Starting the application...
2024-12-12 15:16:17,273 - INFO - Starting the application...
2024-12-12 15:16:26,727 - INFO - Starting the application...
2024-12-12 16:11:40,757 - INFO - Running the application...
2024-12-12 16:11:40,783 - INFO - Starting up the application...
2024-12-12 16:11:40,783 - INFO - Endpoint /transfer is now online
